### ISSUE TITLE
Function import_omnipath_interactions()

### ISSUE THREAD

**Issue by elenu** [saezlab/NicheNet_Omnipath#2]
Good afternoon, :)

I have been trying to reproduce the 01_SourceComparison.Rmd script, but I always have an error when it's necessary to run the import_omnipath_interactions() function: "Error in open.connection(5L, "rb") : HTTP error 500. Calls: <Anonymous> ... <Anonymous> -> vroom_ -> <Anonymous> -> open.connection"

I have reinstalled OmnipathR in the different ways the authors suggested in their website <https://saezlab.github.io/OmnipathR/index.html>. Despite I can load the library, I cannot run this function, though.

Thank you in advance.

Best,
Elena

**Comment by alberto-valdeolivas** [comment]
Hello @elenu,

Thanks for your interest in our repo. 

Can you run the other _OmniPathR_ functions present in the script? such as `import_ligrecextra_interactions()` or `import_omnipath_intercell()`. I assume that this is a general connection problem to the web service. @deeenes have you seen something like this before? 

Best,
Alberto.

**Comment by elenu** [comment]
Hello @alberto-valdeolivas ,

Thank you for your prompt response.

It might have been a connection problem as you mention, because I can run it today.

The only thing I couldn't do is loading the DoRothEA/database.csv table (I couldn't find the enclosed https link, neither). But I already have seen the other network comparisons and I would proceed to try it with my own data.

Thank you!

Best,
Elena

**Comment by ama-va** [comment]
Hi Elana,

Before yesterday our server experienced some service disruptions due to a disk running out of space. Apologies for the inconvenience, please let us know if you are still experiencing any issue.

Best,

Denes

**Comment by deeenes** [comment]
Hi Elena,

Before yesterday our server experienced some service disruptions due to a disk running out of space. Apologies for the inconvenience and please let us know if you are still experiencing any issue.

About running NicheNet: after we published this tutorial, we added a number of functions to `OmnipathR` which build NicheNet database knowledge with high flexibility and even help to run the NicheNet workflow. See here all the functions prefixed by `nichenet_`: https://saezlab.github.io/OmnipathR/reference/index.html and this vignette: https://saezlab.github.io/OmnipathR/articles/nichenet.html

Best,

Denes
